name: build html report

on:
  push:
  workflow_dispatch:

jobs:
  build-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: build html
        run: |
          cd reports
          go run ./cmd/build-html
          mv _site ../
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-pages-artifact@v2
      - name: deploy GitHub Pages
        uses: actions/deploy-pages@v2
        if: github.ref == 'refs/heads/main'