name: build

on: [push]

jobs:
  self-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SDK:
          - web5-js
          - web5-kt
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: self test
        run: go run ./cmd/web5-spec-test sdks/$SDK
        env:
          SDK: ${{ matrix.SDK }}
